<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <PublishAot>true</PublishAot>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <DeterministicBuild>true</DeterministicBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.2.11" />
    <PackageReference Include="Bogus" Version="35.6.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Pulse/Pulse.csproj" />
    <Using Include="Bogus"/>
  </ItemGroup>
</Project>
